modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
issueTrackerURL="https://github.com/onVoid/SteelsDelight/issues"


[[mods]]
modId="steelsdelight"
version="${file.jarVersion}"
displayName="Steel's Delight"
displayURL="https://www.curseforge.com/minecraft/mc-mods/steels-delight"
updateJSONURL="https://onvoid.net/steelsdelight/update.json"
logoFile="steelsdelight.png"
logoBlur=false
credits="vectorwing - Farmer's Delight creator"
authors="onVoid"
description="Adds a Steel Knife to Farmer's Delight."
itemIcon="steelsdelight:steel_knife"
configBackground="minecraft:textures/block/bricks.png"

[[dependencies.steelsdelight]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.steelsdelight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.18.1-1.0.3,]"
    ordering="AFTER"
    side="BOTH"